#!/usr/bin/env python3
'IRC client v2'


from client_class   import IRCclient
from sys            import argv, version_info, exit
from time           import sleep
from syntax         import syntax
from round_robin    import round_robin
from time_calc      import now
from xterm_control  import clear



if __name__ == "__main__":

    # check python

    if version_info < (3, 10):
        exit('Python 3.10 or later required .')


    # cli argument / syntax

    profile_name = syntax(argv)


    # create client object

    client = IRCclient(profile_name)

    print(now(), '*', 'client established .')



    # main reconnect loop

    while 1:

        client.sock_connect()


        if not client.connected: # connect failed

            if round_robin(client): continue


        else: # connect successful

            client.register()

            client.sock_read() # loop / blocking

            print(now(), '*', 'lost connection .')


        # reconnect?

        if client.reconnect:

            print(now(), '*', f'reconnect in {client.reconnect} sec …')

            try: sleep(client.reconnect)

            except KeyboardInterrupt:

                print(clear(), end=''); exit()

            continue


        else: exit(0)

